=== patrodyne/hisrc-basicjaxb/higher/tests/simple/src/main/resources/organization.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="urn:jvnet.org:basicjaxb:tests:simple:model"
	xmlns:tns="urn:jvnet.org:basicjaxb:tests:simple:model"
	xmlns:anx="urn:jvnet.org:basicjaxb:xjc:annox"
	xmlns:jaxb="https://jakarta.ee/xml/ns/jaxb"
	jaxb:extensionBindingPrefixes="anx"
	jaxb:version="3.0"
>
	<xs:complexType name="Department">
		<xs:sequence>
			<xs:element name="id" type="xs:ID" minOccurs="1"/>
			<xs:element name="name" type="xs:string"/>
			<!-- 
			<xs:element name="employeeRefs" type="xs:IDREFS" minOccurs="0">
				<xs:annotation>
	                <xs:appinfo>
	                    <jaxb:property>
                            <jaxb:baseType name="org.jvnet.basicjaxb.tests.simple.model.Employee" />
                        </jaxb:property>
	                </xs:appinfo>
            	</xs:annotation>
            </xs:element>
			 -->
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Project">
		<xs:sequence>
			<xs:element name="id" type="xs:ID" minOccurs="1"/>
			<xs:element name="projectName" type="xs:string"/>
			<xs:element name="employees" type="xs:IDREF" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:appinfo>
						<jaxb:class ref="org.jvnet.basicjaxb.tests.simple.model.Employee"/>
						<anx:annotate target="field">@jakarta.xml.bind.annotation.XmlIDREF</anx:annotate>
						<!-- 
							WARN: This generates @XmlElementRef on Employee#projects and 
							@XmlElementDecl and @XmlIDREF in the ObjectFactory which then
							adds a JAXBElement wrapper.
	                    <jaxb:property>
                            <jaxb:baseType name="org.jvnet.basicjaxb.tests.simple.model.Employee" />
                        </jaxb:property>
						 -->
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Employee">
		<xs:sequence>
			<xs:element name="id" type="xs:ID" minOccurs="1"/>
			<xs:element name="lastName" type="xs:string"/>
			<xs:element name="active" type="xs:boolean"/>
			<xs:element name="department" type="xs:IDREF" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:appinfo>
						<!-- 
						<jaxb:class ref="Department"/>
						 -->
	                    <jaxb:property>
                            <jaxb:baseType name="org.jvnet.basicjaxb.tests.simple.model.Department" />
                        </jaxb:property>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
			<xs:element name="projects" type="xs:IDREF" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:appinfo>
						<jaxb:class ref="org.jvnet.basicjaxb.tests.simple.model.Project"/>
						<anx:annotate target="field">@jakarta.xml.bind.annotation.XmlIDREF</anx:annotate>
						<!--
							WARN: This generates @XmlElementRef on Employee#projects and 
							@XmlElementDecl and @XmlIDREF in the ObjectFactory which then
							adds a JAXBElement wrapper.
		                    <jaxb:property>
	                            <jaxb:baseType name="org.jvnet.basicjaxb.tests.simple.model.Project" />
	                        </jaxb:property>
						 -->
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="Organization">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:string" minOccurs="1"/>
				<xs:element name="departments" type="tns:Department" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="projects" type="tns:Project" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="employees" type="tns:Employee" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== patrodyne/hisrc-basicjaxb/higher/tests/simple/src/test/samples/Organization01.xml
<?xml version="1.0" encoding="UTF-8"?>
<Organization 
	xmlns="urn:jvnet.org:basicjaxb:tests:simple:model" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:jvnet.org:basicjaxb:tests:simple:model ../../main/resources/organization.xsd"
>

	<id>ORG01</id>

	<!-- 4 Departments -->
	<departments>
		<id>DE-ENG</id>
		<name>Engineering</name>
	</departments>
	<departments>
		<id>DE-FIN</id>
		<name>Finance</name>
	</departments>
	<departments>
		<id>DE-HR</id>
		<name>Human Resources</name>
	</departments>
	<departments>
		<id>DE-MKT</id>
		<name>Marketing</name>
	</departments>
	
	<!-- 2 Projects -->
	<projects>
		<id>PR-APO</id>
		<projectName>Apollo</projectName>
	</projects>
	<projects>
		<id>PR-ZEU</id>
		<projectName>Zeus</projectName>
	</projects>

	<!-- 8 Employees -->
	<employees>
		<id>EM-BRO01</id>
		<lastName>Brown</lastName>
		<active>false</active>
		<department>DE-MKT</department>
	</employees>
	<employees>
		<id>EM-DAV01</id>
		<lastName>Davis</lastName>
		<active>true</active>
		<department>DE-FIN</department>
	</employees>
	<employees>
		<id>EM-GAR01</id>
		<lastName>Garcia</lastName>
		<active>true</active>
		<department>DE-HR</department>
	</employees>
	<employees>
		<id>EM-JOH01</id>
		<lastName>Johnson</lastName>
		<active>true</active>
		<department>DE-ENG</department>
		<projects>PR-APO</projects>
	</employees>
	<employees>
		<id>EM-JON01</id>
		<lastName>Jones</lastName>
		<active>true</active>
		<department>DE-HR</department>
	</employees>
	<employees>
		<id>EM-MIL01</id>
		<lastName>Miller</lastName>
		<active>true</active>
		<department>DE-FIN</department>
		<projects>PR-ZEU</projects>
	</employees>
	<employees>
		<id>EM-SMI01</id>
		<lastName>Smith</lastName>
		<active>true</active>
		<department>DE-ENG</department>
		<projects>PR-APO</projects>
		<projects>PR-ZEU</projects>
	</employees>
	<employees>
		<id>EM-WIL01</id>
		<lastName>Williams</lastName>
		<active>true</active>
		<department>DE-MKT</department>
		<projects>PR-ZEU</projects>
	</employees>

</Organization>
